import Head from 'next/head'
import React, { useState } from 'react';
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css'




export default function Home() {

  const [id, setId] = React.useState();
  const router = useRouter();

  const handleChange = (e) => {
    setId(e.target.value);
  }
  
  const handleSubmit=()=>{
    router.push({pathname:'/news',query:{id:id}})
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="Open Graph Meta Tags: Everything You Need to Know" />
        <meta property="og:url" content="https://63a6ad0ab865f341a351c47e--profound-alpaca-ba9d44.netlify.app/" />
        <meta property="og:image" content="https://www.gstatic.com/webp/gallery3/1.png" />
        <meta property="og:image:width" content="600" />
        <meta property="og:image:height" content="600" />
        <meta property="og:type" content="website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>Main Page</div>
        <input onChange={handleChange} value={id} />
        <button onClick={handleSubmit}>submit</button>
      </main>
    </>
  )
}
